// This file was generated by Slater.app - Exhibitions.js

// Back link
const backLinks = document.querySelectorAll('.nav_back_link');
backLinks.forEach(link => {
  link.addEventListener('click', event => {
    event.preventDefault();
    window.history.back();
  });
});

// Select the necessary elements
const container = document.querySelector('.show_inner');
const showItems = document.querySelectorAll('.show_item');
const images = document.querySelectorAll('.show_img');
const toggleButton = document.querySelector('.nav_toggle'); // Updated selector

let isGridView = false;

// Function to reset transformations
function resetTransformations() {
  showItems.forEach(item => {
    gsap.set(item, { clearProps: "all" });
  });
}

// Function to show Grid View
function showGridView() {
  console.log("Switching to Grid View");

  gsap.to(showItems, {
    scale: 0.9,
    opacity: 0,
    duration: 0.5,
    ease: "power2.inOut",
    onComplete: () => {
      window.scrollTo(0, 0);

      // Switch container classes for grid view